cloud:
  aws:
    credentials:
      access-key: AKIARLZEDVJ7RNDIMWCT
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: pintbid


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB