cloud:
  aws:
    credentials:
      access-key: // your own AWS access key
      secret-key: // your own secret key
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: pintbid


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB